#================================= Imports ===================================#
import numpy as np
import scipy.integrate as spint
import matplotlib.pyplot as plt

#=========================== Global variables ================================#
rinit, rmax = 0., 0.99999
grid = 1024

#============================= Magnetic field ================================#
#   Define magnetic field inside of the unit disc generated by a circular wire
# constant current of I A running through it counter-clockwise.
#   Use Biot-Savart formula, leave out the current constant I for later.

def B(r):
    ''' Use Biot-Savart formula with current I = 1A.'''
    
    def integrand(t):
        num, den = (r*np.cos(t) - 1), (1 + r**2 - 2*r*np.cos(t))**(3/2)  
        return -10**(-7)*num/den
        
    return spint.quad(integrand, 0, 2*np.pi)
    
#================================== Set up ===================================#    
# r-axis
r = np.linspace(rinit, rmax, grid)

# Integrate magnetic field
bb = np.array([B(s) for s in r])

# Define current
I =1

# Magnetic field b, and integral error e
b, e = I*bb[:,0], bb[:,1]

# Comparison function c
c = np.array([(10**(-7)*I*2)/(1-s) for s in r])

#=================================== Plot ====================================#
# Create figure
fig, ax = plt.subplots()

# Plot difference
ax.plot(r,b-c,'b-',lw=2)

# Plot magnetic field and comparison function
#ax.plot(r,c,'g-',lw=2)
#ax.plot(r,b,'r-',lw=2)

# Plot integral's numerical error
ax.plot(r,e,'r-',lw=2)

plt.savefig('biotsavarterror.jpg')